test: True

filter:
  thing_type: shelly:shellyflood


channels:
  - filter:
      channel_uid: .+sensors#temperature$
    link items:
      - type: Number
        name: '{thing_label, :(.+)$}_Temperatur'
        label: '{thing_label, :(.+)$} Temperatur [%.1f °C]'

  - filter:
      channel_uid: .+sensors#flood$
    link items:
      - type: Switch
        name: '{thing_label, :(.+)$}_Alarm'
        label: '{thing_label, :(.+)$} Alarm [%s]'

  - filter:
      channel_uid: .+sensors#batteryLevel$
    link items:
      - type: Number
        name: '{thing_label, :(.+)$}_Batterie'
        label: '{thing_label, :(.+)$} Batterie [%d %%]'

  - filter:
      channel_uid: .+device#alarm$
    link items:
      - type: Number
        name: '{thing_label, :(.+)$}_Ereignis'
        label: '{thing_label, :(.+)$} Ereignis [%s]'
