version : 1


formatters:
  HABApp_format:
    format: '[%(asctime)s] [%(name)25s] %(levelname)8s | %(message)s'


handlers:
  HABApp_default:
    class: logging.handlers.RotatingFileHandler
    filename: 'HABApp.log'
    maxBytes: 10_000_000
    backupCount: 3

    formatter: HABApp_format
    level: DEBUG

  EventFile:
    class: logging.handlers.RotatingFileHandler
    filename: 'events.log'
    maxBytes: 10_485_760
    backupCount: 3

    formatter: HABApp_format
    level: DEBUG

  HABApp_test_file:
    class: logging.handlers.RotatingFileHandler
    filename: 'tests.log'
    maxBytes: 10_485_760
    backupCount: 3

    formatter: HABApp_format
    level: DEBUG

  HABApp_rest_file:
    class: logging.handlers.RotatingFileHandler
    filename: 'test_rest.log'
    maxBytes: 10_485_760
    backupCount: 3

    formatter: HABApp_format
    level: DEBUG

  BufferEventFile:
    class: logging.handlers.MemoryHandler
    capacity: 0
    formatter: HABApp_format
    target: EventFile
    level: DEBUG


loggers:
  HABApp:
    level: DEBUG
    handlers:
      - HABApp_default
    propagate: False

  HABApp.Shutdown:
    level: DEBUG
    handlers:
      - HABApp_default
    propagate: False

  HABApp.openhab:
    level: DEBUG
    handlers:
      - HABApp_default
    propagate: False

  HABApp.EventBus:
    level: DEBUG
    handlers:
      - BufferEventFile
    propagate: False

  HABApp.Tests:
    level: DEBUG
    handlers:
      - HABApp_test_file
    propagate: False

  HABApp.Rest:
    level: DEBUG
    handlers:
      - HABApp_rest_file
    propagate: False
