version : 1


formatters:
  HABApp_format:
    format: '[%(asctime)s] [%(name)25s] %(levelname)8s | %(message)s'


handlers:
  HABApp_default:
    class: logging.handlers.RotatingFileHandler
    filename: 'z:/Python/HABApp/conf/log/HABApp.log'
    maxBytes: 10_000_000
    backupCount: '3'

    formatter: HABApp_format
    level: DEBUG

  EventFile:
    class: logging.handlers.RotatingFileHandler
    filename: 'z:/Python/HABApp/conf/log/events.log'
    maxBytes: 10_485_760
    backupCount: 3

    formatter: HABApp_format
    level: DEBUG

  BufferEventFile:
    class: logging.handlers.MemoryHandler
    capacity: 10
    formatter: HABApp_format
    target: EventFile
    level: DEBUG


loggers:
  HABApp:
    level: DEBUG
    handlers:
      - HABApp_default
    propagate: False

  HABApp.Shutdown:
    level: DEBUG
    handlers:
      - HABApp_default
    propagate: False

  HABApp.openhab:
    level: DEBUG
    handlers:
      - HABApp_default
    propagate: False

  HABApp.EventBus:
    level: DEBUG
    handlers:
      - BufferEventFile
    propagate: False
